### ISSUE TITLE
Requests from the team

### ISSUE THREAD

**Issue by dirkkelly** [dsafc/dsafc#4]
- Our email address (at the top little mail icon) currently links to fortcollinsdsa@gmail.com, and that needs to be changed to dsafortcollins@gmail.com
- On the ‘Meetings’ tab, can you change the info in Education Committee to remove ‘Ask Jake’ (I don’t think that’s particularly helpful), and update the ‘Wednesday at 630pm’ to ‘Thursday at 6:30pm’
-  And on that same ‘Meetings’ tab, can you add something to say, ‘Check our Twitter and Facebook for more information on our events’

**Comment by ozzyaaron** [comment]
Who usually is responsible for closing these? Seems like this is probably where 'QA' could happen. e.g. Emily can close this issue to confirm everything was done properly.

**Comment by dirkkelly** [comment]
Good q. Creator or admin usually. Feel free to if you see one that’s done.
